#!/usr/bin/env python3
"""Synchronize configured harness skill trees from the canonical skills directory."""

from __future__ import annotations

import argparse
import filecmp
import os
import re
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Any

import yaml

MARKER_NAME = ".generated-by-sync-harness-skills"
MARKER_CONTENT = "Generated by scripts/sync_harness_skills.py. Do not edit.\n"
HARNESS_NAME = re.compile(r"^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$")
RESERVED_OUTPUT_NAMES = {
    ".git",
    ".github",
    "AGENTS.md",
    "LICENSE",
    "README.md",
    "harnesses.yaml",
    "requirements.txt",
    "scripts",
    "skills",
    "tests",
}


class SyncError(Exception):
    """Raised for invalid configuration, source inventory, or unsafe output state."""


class UniqueKeyLoader(yaml.SafeLoader):
    """Safe YAML loader that rejects duplicate mapping keys at every nesting level."""


def _construct_mapping(loader: UniqueKeyLoader, node: yaml.MappingNode, deep: bool = False) -> dict[Any, Any]:
    mapping: dict[Any, Any] = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node, deep=deep)
        if key in mapping:
            raise SyncError(f"duplicate YAML key: {key!r}")
        mapping[key] = loader.construct_object(value_node, deep=deep)
    return mapping


UniqueKeyLoader.add_constructor(
    yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, _construct_mapping
)


def _is_regular_file(path: Path) -> bool:
    return path.is_file() and not path.is_symlink()


def _marker_is_owned(output_root: Path) -> bool:
    marker = output_root / MARKER_NAME
    try:
        return _is_regular_file(marker) and marker.read_text(encoding="utf-8") == MARKER_CONTENT
    except OSError:
        return False


def _validate_source_tree(source_dir: Path) -> None:
    for current, directories, files in os.walk(source_dir, followlinks=False):
        current_path = Path(current)
        for name in directories + files:
            path = current_path / name
            if path.is_symlink():
                raise SyncError(f"source skill contains unsupported symlink: {path}")
            if not path.is_dir() and not path.is_file():
                raise SyncError(f"source skill contains unsupported path type: {path}")


def inventory_skills(repo_root: Path) -> list[str]:
    skills_root = repo_root / "skills"
    if skills_root.is_symlink() or not skills_root.is_dir():
        raise SyncError(f"skills source directory is missing or unsafe: {skills_root}")

    names: list[str] = []
    for entry in sorted(skills_root.iterdir(), key=lambda path: path.name):
        if entry.name == ".gitkeep":
            continue
        if entry.is_symlink():
            raise SyncError(f"source skill entry cannot be a symlink: {entry}")
        if not entry.is_dir():
            continue
        skill_file = entry / "SKILL.md"
        if not _is_regular_file(skill_file):
            raise SyncError(f"source skill is missing a regular SKILL.md: {entry.name}")
        _validate_source_tree(entry)
        names.append(entry.name)
    return names


def _load_config(config_path: Path, inventory: list[str]) -> dict[str, list[str]]:
    try:
        content = config_path.read_text(encoding="utf-8")
    except OSError as error:
        raise SyncError(f"cannot read config {config_path}: {error}") from error

    try:
        document = yaml.load(content, Loader=UniqueKeyLoader)
    except (yaml.YAMLError, SyncError) as error:
        raise SyncError(f"invalid YAML in {config_path}: {error}") from error

    if not isinstance(document, dict) or set(document) != {"harnesses"}:
        raise SyncError("config top level must be a mapping containing exactly 'harnesses'")
    harnesses = document["harnesses"]
    if not isinstance(harnesses, dict) or not harnesses:
        raise SyncError("'harnesses' must be a non-empty mapping")

    available = set(inventory)
    selections: dict[str, list[str]] = {}
    for harness, entry in harnesses.items():
        if not isinstance(harness, str) or not HARNESS_NAME.fullmatch(harness):
            raise SyncError(f"unsafe harness name: {harness!r}")
        if harness in RESERVED_OUTPUT_NAMES:
            raise SyncError(f"harness name is reserved: {harness}")
        if not isinstance(entry, dict):
            raise SyncError(f"harness {harness!r} must be a mapping")
        unknown_keys = set(entry) - {"include", "exclude"}
        if unknown_keys:
            raise SyncError(f"harness {harness!r} has unknown keys: {sorted(unknown_keys)}")

        lists: dict[str, list[str]] = {}
        for key in ("include", "exclude"):
            if key not in entry:
                continue
            value = entry[key]
            if not isinstance(value, list) or any(not isinstance(item, str) for item in value):
                raise SyncError(f"harness {harness!r} {key} must be an array of strings")
            if len(value) != len(set(value)):
                raise SyncError(f"harness {harness!r} {key} contains duplicate skill names")
            unknown_skills = set(value) - available
            if unknown_skills:
                raise SyncError(
                    f"harness {harness!r} {key} references unknown skills: {sorted(unknown_skills)}"
                )
            lists[key] = value

        selected = set(lists.get("include", inventory)) - set(lists.get("exclude", []))
        selections[harness] = [name for name in inventory if name in selected]
    return selections


def _validate_existing_outputs(repo_root: Path, harnesses: set[str]) -> set[str]:
    marked_outputs: set[str] = set()
    try:
        entries = list(repo_root.iterdir())
    except OSError as error:
        raise SyncError(f"cannot inspect repository root {repo_root}: {error}") from error

    for entry in entries:
        if entry.is_symlink():
            if entry.name in harnesses:
                raise SyncError(f"configured output root is a symlink: {entry.name}")
            continue
        if entry.is_dir() and _marker_is_owned(entry):
            marked_outputs.add(entry.name)

    for harness in harnesses:
        output = repo_root / harness
        if output.exists() or output.is_symlink():
            if output.is_symlink():
                raise SyncError(f"configured output root is a symlink: {harness}")
            if not output.is_dir() or not _marker_is_owned(output):
                raise SyncError(f"configured output collides with unmarked path: {harness}")
    return marked_outputs


def _copy_source_skill(source: Path, destination: Path) -> None:
    shutil.copytree(source, destination, copy_function=shutil.copy2)


def _build_expected_outputs(
    repo_root: Path,
    staging_root: Path,
    selections: dict[str, list[str]],
) -> dict[str, Path]:
    expected: dict[str, Path] = {}
    source_root = repo_root / "skills"
    for harness, skills in selections.items():
        output = staging_root / harness
        output.mkdir()
        (output / MARKER_NAME).write_text(MARKER_CONTENT, encoding="utf-8")
        for skill in skills:
            _copy_source_skill(source_root / skill, output / skill)
        expected[harness] = output
    return expected


def _path_type(path: Path) -> str:
    if path.is_symlink():
        return "symlink"
    if path.is_dir():
        return "directory"
    if path.is_file():
        return "file"
    return "other"


def _trees_equal(expected: Path, actual: Path) -> bool:
    if not actual.exists() or actual.is_symlink() or not actual.is_dir():
        return False
    expected_paths = sorted(path.relative_to(expected) for path in expected.rglob("*"))
    actual_paths = sorted(path.relative_to(actual) for path in actual.rglob("*"))
    if expected_paths != actual_paths:
        return False
    for relative in expected_paths:
        expected_path = expected / relative
        actual_path = actual / relative
        if _path_type(expected_path) != _path_type(actual_path):
            return False
        if expected_path.is_file():
            if not filecmp.cmp(expected_path, actual_path, shallow=False):
                return False
            if bool(expected_path.stat().st_mode & 0o111) != bool(actual_path.stat().st_mode & 0o111):
                return False
    return True


def _apply_outputs(
    repo_root: Path,
    expected: dict[str, Path],
    marked_outputs: set[str],
) -> list[str]:
    changed = [
        name for name, staging in expected.items() if not _trees_equal(staging, repo_root / name)
    ]
    removed = sorted(marked_outputs - set(expected))
    if not changed and not removed:
        return []

    backup_root = Path(tempfile.mkdtemp(prefix=".sync-harness-backup-", dir=repo_root))
    moved_originals: dict[str, Path] = {}
    placed: list[str] = []
    try:
        for name in sorted(set(changed) | set(removed)):
            existing = repo_root / name
            if existing.exists():
                backup = backup_root / name
                shutil.move(str(existing), str(backup))
                moved_originals[name] = backup
        for name in changed:
            shutil.move(str(expected[name]), str(repo_root / name))
            placed.append(name)
    except OSError as error:
        for name in placed:
            generated = repo_root / name
            if generated.exists():
                shutil.rmtree(generated)
        for name, backup in moved_originals.items():
            if backup.exists():
                shutil.move(str(backup), str(repo_root / name))
        raise SyncError(f"failed to replace generated outputs: {error}") from error
    finally:
        shutil.rmtree(backup_root, ignore_errors=True)
    return sorted(changed + removed)


def synchronize(repo_root: Path, config_path: Path | None = None, check: bool = False) -> tuple[int, list[str]]:
    """Validate then synchronize outputs. Return an exit code and affected harness names."""
    repo_root = repo_root.resolve()
    if config_path is None:
        config_path = repo_root / "harnesses.yaml"
    elif not config_path.is_absolute():
        config_path = repo_root / config_path

    inventory = inventory_skills(repo_root)
    selections = _load_config(config_path, inventory)
    marked_outputs = _validate_existing_outputs(repo_root, set(selections))

    with tempfile.TemporaryDirectory(prefix=".sync-harness-stage-", dir=repo_root) as temporary:
        expected = _build_expected_outputs(repo_root, Path(temporary), selections)
        drift = sorted(
            [name for name, staging in expected.items() if not _trees_equal(staging, repo_root / name)]
            + list(marked_outputs - set(expected))
        )
        if check:
            for name in drift:
                print(f"drift: {name}", file=sys.stderr)
            return (1 if drift else 0), drift
        changed = _apply_outputs(repo_root, expected, marked_outputs)
        return 0, changed


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report drift without modifying outputs")
    parser.add_argument("--config", default="harnesses.yaml", help="config path relative to repository root")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    try:
        args = parse_args(sys.argv[1:] if argv is None else argv)
        repository_root = Path(__file__).resolve().parent.parent
        exit_code, _ = synchronize(repository_root, Path(args.config), args.check)
        return exit_code
    except (SyncError, OSError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
